services:
  digital-bank:
    container_name: digital-bank
    image: digital-bank
    build: .
    restart: always
    command: nodemon --exec go run ./cmd/main.go --signal SIGTERM
    environment:
      GO_ENV: local

      REDIS_HOST: digital-bank-redis:6379

      AWS_REGION: sa-east-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

    volumes:
      - ./:/app

    ports:
      - "3200:8080"

    depends_on:
      - digital-bank-redis

    networks:
      - main

  digital-bank-redis:
    image: redis:latest
    container_name: digital-bank-redis
    networks:
      - main

networks:
  main:
